name: DeployToECR

on:
  workflow_dispatch:
    inputs:
      selected-region:
        type: choice
        description: Select AWS Region
        options:
          - us-east-1

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    steps:
      - name: Sync repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.selected-region }}

      - name: Authenticate with Amazon ECR
        id: ecr-auth
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and upload image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-auth.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
